### ISSUE TITLE
Triggering alert for "Loki pod not ready" due to rescheduling of the pod and slow disk detach/attach 

### ISSUE THREAD

**Issue by vlvasilev** [gardener/logging#86]
**What would you like to be added**:
Currently,  on Azure we have an issue with slow disk detach/attach.
Loki pod is unable to start up to 30 minutes after its creation due to slow disk detaching from the old node and attaching to the new node. To prevent this from happening we have to prevent the pod from rescheduling as much as we can.

1. When garden/loki-0 pod is working on the low utilized node and the Cluster Autoscaler decides to scale down the cluster, the pod is rescheduled to another node. This can be mitigated with the `SeedKubeScheduler` feature gate
Possible solutions.
- Tell the CA to not scale down a node that has the garden/loki-0 pod working on it.
- Make a node pool of only one node for the garden/loki-0 pod where Loki has the highest priority with preemption capability.
  On this node, all other pods will be allowed to be scheduled.
- Move only garden/loki-0 pod to the etcd node pool
- This can be mitigated with the `SeedKubeScheduler` feature gate and for greater efficiency can be combined with one of the other proposals.

2. When garden/loki-0 pod is scale-in by the HVPA.
Possible solutions.
- Make HVPA more passive when it comes to scale-in the garden/loki-0 pod.
- Make HVPA to scale-in the garden/loki-0 pod when the seed is not under high load.

3. When garden/loki-0 pod is preempted due to low priority class.
- Set PriorityClass for Loki(e.g. 40)

4. Alter the "LokiDown" alert 
- Increase the triggering time of the alert.
  -  pros: It will reduce the alerts due to the slow disk detach/attach.
  -  cons: This will cause a potential silent loss of logs related to the seed.

- Removing the alert at all.
  -  pros: There will be no alert at all. No alert, no problem. 
  -  cons: We will not be able to monitor real problems with the Loki pod

**Why is this needed**:
First triggering such alerts will lead to neglect when a real issue occurs.
Stop moving the Loki pod across the nodes will prevent losing logs due to fluent-bit retries timeout.

**Comment by vlerenc** [comment]
@vlvasilev Since @mvladev will introduce bin-packing and Azure will improve attach/detach times eventually, so I would suggest:
1. Of these options, either do nothing or move only `garden/loki-0` to the ETCD node pool with the help of @amshuman-kr 
2. Yes, we can be more conservative when scaling down `garden/loki-0` as that's only one pod and will not drive costs
3. That would be above regular controllers and below API servers/ETCDs, so that sounds about right, but it's below fluentbit - shouldn't `garden/loki-0` be rather above, e.g. 60?
4. Yes, we should definitely increase the alert grace period. We should not remove it - we still want to know of some principle problem. And, it's no real disadvantage (quote: "cons: will cause a potential silent loss of logs related to the seed"), because the alert is not responsible for losing the logs. It's the setup, Azure, the scale-in/down. We would miss the logs whatever the alert grace period, so I see only the positive side of this.

**Comment by Kristian-ZH** [comment]
Since we did all the changes mentioned above, I thing that we can close this issue

/close
